[package]
name = "gitblob"
version = "0.1.0"
authors = ["samlh"]
edition = "2018"

[dependencies]
git2 = "0.9"
gotham = "0.3.0"
gotham_derive = "0.3.0"
hyper = "0.12"
mime = "0.3.13"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"